# Boost +9 dB mit Limiter -4 dBFS für AirPlay (Raspotify hat das eingebaut).
pcm.boost {
  type plug
  slave.pcm "boost_limiter"
}
pcm.boost_limiter {
  type ladspa
  slave.pcm "plughw:CARD=Headphones,DEV=0"
  path "/usr/lib/ladspa"
  plugins [
    {
      label fastLookaheadLimiter
      input { controls [ 9 -4 0.05 ] }
    }
  ]
}
