general = {
  name = "Wohnzimmer";
};
alsa = {
  output_device = "boost";
};
metadata = {
  enabled = "yes";
  include_cover_art = "yes";
  pipe_name = "/run/nowplaying/airplay-metadata";
  pipe_timeout = 5000;
};
